version: '2'

plugins:
  duplication:
    enabled: true
    config:
      languages:
        - 'javascript'
  fixme:
    enabled: true
  eslint:
    enabled: true

exclude_patterns:
  - 'dist/'
  - 'node_modules/'
