env:
  global:
    - CC_TEST_REPORTER_ID=fe076667e24b7715085a4ef599c51391a2e84239557c866b3e6ec7a492d7bbbd
language: node_js
node_js:
  - lts/*
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - yarn test --coverage
after_script:
  - ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $TRAVIS_TEST_RESULT
